//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muxar.BrightStarDb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EchonestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EchonestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Muxar.BrightStarDb.EchonestResources", typeof(EchonestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;artist=.
        /// </summary>
        internal static string ArtistPath {
            get {
                return ResourceManager.GetString("ArtistPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;type=artist-radio.
        /// </summary>
        internal static string ArtistRadioType {
            get {
                return ResourceManager.GetString("ArtistRadioType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artists.
        /// </summary>
        internal static string Artists {
            get {
                return ResourceManager.GetString("Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;id=.
        /// </summary>
        internal static string IdUriPath {
            get {
                return ResourceManager.GetString("IdUriPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;format=json.
        /// </summary>
        internal static string JsonFormat {
            get {
                return ResourceManager.GetString("JsonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;limit=true.
        /// </summary>
        internal static string LimitPath {
            get {
                return ResourceManager.GetString("LimitPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;name=.
        /// </summary>
        internal static string NameUriPath {
            get {
                return ResourceManager.GetString("NameUriPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to official_url.
        /// </summary>
        internal static string OfficialWebsite {
            get {
                return ResourceManager.GetString("OfficialWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playlist/static?.
        /// </summary>
        internal static string PlaylistPath {
            get {
                return ResourceManager.GetString("PlaylistPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to response.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;results=40.
        /// </summary>
        internal static string ResultsPath {
            get {
                return ResourceManager.GetString("ResultsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artist/search?.
        /// </summary>
        internal static string SearchArtist {
            get {
                return ResourceManager.GetString("SearchArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;bucket=id:spotify.
        /// </summary>
        internal static string SpotifyBucket {
            get {
                return ResourceManager.GetString("SpotifyBucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;bucket=tracks.
        /// </summary>
        internal static string TracksBucket {
            get {
                return ResourceManager.GetString("TracksBucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urls.
        /// </summary>
        internal static string Urls {
            get {
                return ResourceManager.GetString("Urls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;variety=1.
        /// </summary>
        internal static string VarietyPath {
            get {
                return ResourceManager.GetString("VarietyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artist/urls?.
        /// </summary>
        internal static string WebsiteArtist {
            get {
                return ResourceManager.GetString("WebsiteArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wikipedia_url.
        /// </summary>
        internal static string Wiki {
            get {
                return ResourceManager.GetString("Wiki", resourceCulture);
            }
        }
    }
}
