//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muxar.BrightStarDb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SparqlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SparqlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Muxar.BrightStarDb.SparqlResources", typeof(SparqlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artistName.
        /// </summary>
        internal static string ArtistName {
            get {
                return ResourceManager.GetString("ArtistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains(lcase(str(?g)), &apos;{0}&apos;) ||.
        /// </summary>
        internal static string ContainsPattern {
            get {
                return ResourceManager.GetString("ContainsPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @en.
        /// </summary>
        internal static string EnLangQualifier {
            get {
                return ResourceManager.GetString("EnLangQualifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genreLabel.
        /// </summary>
        internal static string GenreLabel {
            get {
                return ResourceManager.GetString("GenreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREFIX rdfs: &lt;http://www.w3.org/2000/01/rdf-schema#&gt;        
        ///PREFIX dbo:  &lt;http://dbpedia.org/ontology/&gt; 
        ///PREFIX sco:    &lt;http://schema.org/&gt;
        ///SELECT DISTINCT ?artist ?artistName min(?g)
        ///WHERE {{
        ///VALUES ?type {{ sco:MusicGroup dbo:MusicalArtist }}
        ///    ?artist a ?type .
        ///    ?artist rdfs:label ?artistName.
        ///    ?artist dbo:genre ?genre .
        ///    ?genre rdfs:label ?g .
        ///
        ///FILTER (lang(?artistName) = &apos;en&apos;) .
        ///FILTER({0})
        ///}}
        ///        GROUP BY ?artist? artistName
        ///ORDER BY ?artistName
        ///LIMIT 100.
        /// </summary>
        internal static string GetArtistsByGenre {
            get {
                return ResourceManager.GetString("GetArtistsByGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREFIX rdfs: &lt;http://www.w3.org/2000/01/rdf-schema#&gt;        
        ///PREFIX dbo:  &lt;http://dbpedia.org/ontology/&gt; 
        ///SELECT DISTINCT ?genreLabel
        ///WHERE {{
        ///?resource dbo:genre ?genre.
        ///?resource rdfs:label &apos;{0}&apos;@en.
        ///?genre rdfs:label? genreLabel
        ///FILTER(lang(?genreLabel) = &apos;en&apos;)
        ///}}
        ///LIMIT 100.
        /// </summary>
        internal static string GetGenresByArtist {
            get {
                return ResourceManager.GetString("GetGenresByArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREFIX rdfs: &lt;http://www.w3.org/2000/01/rdf-schema#&gt;        
        ///                        PREFIX dbo:  &lt;http://dbpedia.org/ontology/&gt; 
        ///                        PREFIX schema:    &lt;http://schema.org/&gt;
        ///                        SELECT distinct ?artist ?artistName
        ///                        WHERE {{
        ///                        VALUES ?type {{ schema:MusicGroup dbo:MusicalArtist }}
        ///                            ?artist a ?type .
        ///                            ?artist rdfs:label ?artistName.
        ///                        FILTER(CO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchArtistsByLabel {
            get {
                return ResourceManager.GetString("SearchArtistsByLabel", resourceCulture);
            }
        }
    }
}
